---
- name: Migrate Metax database
  django_manage:
    command: 'migrate'
    app_path: '{{ repo_path }}/src'
    virtualenv: '{{ directory_venv }}'
  become: yes
  become_user: '{{ application_user }}'
  tags: metax-manage

- name: Index Metax refdata
  django_manage:
    command: 'index_refdata'
    app_path: '{{ repo_path }}/src'
    virtualenv: '{{ directory_venv }}'
  become: yes
  become_user: '{{ application_user }}'
  tags: metax-manage

- name: Index Organization data
  django_manage:
    command: 'update_orgs'
    app_path: '{{ repo_path }}/src'
    virtualenv: '{{ directory_venv }}'
  become: yes
  become_user: '{{ application_user }}'
  tags: metax-manage

- name: Reload Metax refdata cache
  django_manage:
    command: 'reload_refdata_cache'
    app_path: '{{ repo_path }}/src'
    virtualenv: '{{ directory_venv }}'
  become: yes
  become_user: '{{ application_user }}'
  tags: metax-manage

- name: Load Metax test data
  django_manage:
    command: 'loaddata metax_api/tests/testdata/test_data.json'
    app_path: '{{ repo_path }}/src'
    virtualenv: '{{ directory_venv }}'
  become: yes
  become_user: '{{ application_user }}'
  when: application_django_env != 'production'
  tags: metax-manage

- name: Load Metax initial data
  django_manage:
    command: 'loadinitialdata'
    app_path: '{{ repo_path }}/src'
    virtualenv: '{{ directory_venv }}'
  become: yes
  become_user: '{{ application_user }}'
  tags: metax-manage
