---
- name: Install Metax API systemd files
  template:
    src: '{{ item.file }}'
    dest: '{{ item.dest }}'
    mode: '0644'
  with_items:
  - file: 'fairdata-metax.service.j2'
    dest: '/etc/systemd/system/{{ instance_name }}.service'
  - file: 'fairdata-metax.socket.j2'
    dest: '/etc/systemd/system/{{ instance_name }}.socket'
  - file: 'fairdata-metax.env.j2'
    dest: '{{ directory_config }}/fairdata-metax.env'
  - file: 'fairdata-metax-gunicorn.py.j2'
    dest: '{{ directory_config }}/fairdata-metax-gunicorn.py'
  become: yes
  notify: Restart Metax API
  tags: metax-systemd

- name: Ensure Metax API systemd service is started
  systemd:
    name: '{{ item }}'
    state: started
    enabled: yes
    daemon_reload: yes
  with_items:
  - '{{ instance_name }}.service'
  - '{{ instance_name }}.socket'
  become: yes
  tags: metax-systemd
