---
- name: Ensure required yum packages are installed
  yum:
    name:
    - gcc
    - gcc-c++
    - git
    - xqilla
    - xqilla-devel
    - python2-pip
    # state: present, in order not to upgrade any package to an untested version
    state: present
  become: yes
  tags: metax-prerequisites
