---
- name: Ensure OIDC module is installed
  yum:
    name: mod_auth_openidc
    # state: present, in order not to upgrade any package to an untested version
    state: present
  become: yes
  notify: Restart httpd
  tags: metax-httpd

- name: Ensure Metax httpd configurations are correct
  template:
    src: 'fairdata-metax-httpd.conf.j2'
    dest: '/etc/httpd/conf.d/{{ deployment_fqdn }}.conf'
    mode: '0644'
  become: yes
  notify: Restart httpd
  tags: metax-httpd
