---
- name: Ensure that directories exist with correct permissions
  file:
    path: '{{ item }}'
    owner: '{{ application_user }}'
    group: '{{ application_group }}'
    state: 'directory'
    recurse: 'yes'
    mode: '0755'
  with_items:
  - '{{ directory_venv }}'
  - '{{ directory_config }}'
  - '{{ directory_log }}'
  become: yes
  tags: metax-configuration

- name: Create logrotation for Metax API logs
  template:
    src: 'fairdata-metax-logrotation.conf.j2'
    dest: '/etc/logrotate.d/{{ instance_name }}'
    mode: '0644'
  become: yes
  tags: metax-configuration

- name: Install setuptools for pip
  pip:
    name: setuptools==59.6.0
    executable: pip3
  become: yes
  tags: metax-configuration

- name: Install setuptools to virtualenv with pip
  pip:
    name: setuptools==59.6.0
    virtualenv: '{{ directory_venv }}'
    virtualenv_command: '{{ python_virtualenv_command }}'
  become: yes
  become_user: '{{ application_user }}'

- name: Install Metax API requirements in virtualenv with pip
  pip:
    requirements: '{{ repo_path }}/requirements.txt'
    virtualenv: '{{ directory_venv }}'
    virtualenv_command: '{{ python_virtualenv_command }}'
  become: yes
  become_user: '{{ application_user }}'
  notify: Restart Metax API
  tags: metax-configuration

- name: Ensure Metax dotenv file is installed in source repository
  template:
    src: 'fairdata-metax.env.j2'
    dest: '{{ repo_path }}/src/metax_api/settings/.env'
    owner: '{{ application_user }}'
    group: '{{ application_group }}'
    mode: '0644'
  become: yes
  notify: Restart Metax API
  tags: metax-configuration

- name: Ensure Metax api users are defined correctly
  copy:
    dest: '{{ directory_config }}/metax_users.json'
    owner: '{{ application_user }}'
    group: '{{ application_group }}'
    mode: '0644'
    content: '{{ application_api_users | to_nice_json }}'
  become: yes
  notify: Restart Metax API
  tags: metax-configuration

- name: Ensure additional end user permissions are defined
  copy:
    dest: '{{ directory_config }}/additional_projects.json'
    owner: '{{ application_user }}'
    group: '{{ application_group }}'
    mode: '0644'
    content: '{{ application_additional_projects | to_nice_json }}'
  become: yes
  notify: Restart Metax API
  tags: metax-configuration
