---
- name: Ensure Metax API systemd services are stopped and masked
  systemd:
    name: '{{ item }}'
    state: 'stopped'
    masked: 'yes'
    enabled: 'no'
  with_items:
  - '{{ instance_name }}.service'
  - '{{ instance_name }}.socket'
  when: delete_deployment
  ignore_errors: yes
  become: yes
  notify: Reload Systemd Daemon
  tags: metax-delete

- name: Ensure instance files are deleted
  file:
    path: '{{ item }}'
    state: 'absent'
  with_items:
  - '{{ repo_path }}'
  - '/etc/systemd/system/{{ instance_name }}.service'
  - '/etc/systemd/system/{{ instance_name }}.socket'
  - '{{ directory_config }}'
  - '{{ directory_run }}/{{ instance_name }}.sock'
  - '{{ directory_log }}'
  - '{{ directory_venv }}'
  - '/etc/logrotate.d/{{ instance_name }}'
  when: delete_deployment
  become: yes
  notify: Reload Systemd Daemon
  tags: metax-delete

- name: Ensure Nginx configurations are deleted
  file:
    path: '/etc/nginx/{{ item }}/{{ deployment_fqdn }}'
    state: 'absent'
  with_items:
  - 'sites-enabled'
  - 'sites-available'
  when: delete_proxy
  become: yes
  notify: Restart Nginx
  tags: metax-delete

- name: Ensure httpd configurations are deleted
  file:
    path: '/etc/httpd/conf.d/{{ deployment_fqdn }}.conf'
    state: 'absent'
  when: delete_proxy
  become: yes
  notify: Restart httpd
  tags: metax-delete
