---
- name: Ensure log directory exist with correct permissions
  file:
    path: '{{ directory_log }}'
    owner: '{{ application_user }}'
    group: '{{ application_group }}'
    state: 'directory'
    mode: '0755'
  become: yes
  tags: metax-nginx

- name: Ensure passlib pip package is installed
  pip:
    name: 'passlib'
    # state: present, in order not to upgrade any package to an untested version
    state: present
    executable: 'pip2'
  become: yes
  tags: metax-nginx

- name: Install Metax Nginx shared configurations
  template:
    src: 'metax-nginx-shared.conf.j2'
    dest: '/etc/nginx/conf.d/metax-nginx-shared.conf'
    mode: '0644'
  become: yes
  notify: Restart Nginx
  tags: metax-nginx

- name: Install Metax Nginx virtual server definition
  template:
    src: 'fairdata-metax-nginx.conf.j2'
    dest: '/etc/nginx/sites-available/{{ deployment_fqdn }}'
    mode: '0644'
  become: yes
  notify: Restart Nginx
  tags: metax-nginx

- name: Enable Metax Nginx virtual server
  file:
    path: '/etc/nginx/sites-enabled/{{ deployment_fqdn }}'
    src: '/etc/nginx/sites-available/{{ deployment_fqdn }}'
    state: link
  become: yes
  notify: Restart Nginx
  tags: metax-nginx
