---
- name: Build Sphinx documentation
  command:
    cmd: '{{ directory_venv }}/bin/sphinx-build -b html {{ repo_path }}/docs/api {{ repo_path }}/docs/api/build'
  environment:
    DOMAIN: '{{ deployment_fqdn }}'
    BRANCH: '{{ repo_version }}'
    ETSIN_URL: 'etsin.{{ instance_domain }}'
    REMS_ENABLED: '{{ application_rems_enabled }}'
  become: yes
  become_user: '{{ application_user }}'
  tags: metax-docs
