---
- name: Restart Nginx
  systemd:
    name: 'nginx'
    state: 'restarted'
  become: yes

- name: Restart httpd
  systemd:
    name: 'httpd'
    state: 'restarted'
  become: yes

- name: Restart Metax API
  systemd:
    name: 'fairdata-metax'
    state: 'restarted'
  become: yes
